### PR TITLE
Boilerplate: Use functional components as example

### PR DESCRIPTION
**Pull request by jens-ox**

### CODE REVIEW

**Review by harrybin — DISMISSED** [review]

**Comment by ebual** [comment]
Hello @jens-ox thank you for your contribution.
Unfortunately before we can discuss any of your committed changes I need you to sign the Daimler CLA according to the [Contribution Guide](https://github.com/Daimler/mo360-ftk/blob/master/CONTRIBUTING.md).

**Comment by jens-ox** [comment]
Hi @ebual ! Signed and sent it to the given mail address.

Would be great to have a possibility to fill out a CLA online ([see e.g. the facebook one](https://code.facebook.com/cla)).

**Comment by prode81** [comment]
Hey @jens-ox, thank you. And again thank you for your contribution.
As far as we know, we are aiming for an automated CLA Workflow, which currently is not available yet, so we have to work with this workaround for now.

**Comment by jens-ox** [comment]
I also suppose it could be noted in the CLA that the address field is only relevant for company contributions (at least that's my experience with other CLAs)

**Comment by harrybin** [comment]
@jens-ox did you try running any component test, testing a FC using the `useI81n` hook?
I'm unable to test any component using that hook (which is nearly everyone in my case)

**Comment by jens-ox** [comment]
@harrybin I'd suggest opening an issue for that. Also, are you sure that you updated your packages? Package should be `@daimler/ftk-core` and not `@switch/core` as your stacktrace suggests. I assume this comes from not correctly initializing a `TranslationContext` or something like that.

**Comment by jens-ox** [comment]
@ebual from a cla perspective this should now be good to merge, any comments re: review?

**Comment by ebual** [comment]
Yes, I just got the confirmation that the CLA is deposited.

---

I think the idea is great to show the usage of functional components and hooks. But since these boilerplate files are meant to be examples for a possible implementation I think it is important to also show the usage with class based components.
My proposal would be to keep the `Home.tsx` as it is, showcasing the class based approach. And converting the `DemoContent.tsx` to a functional component like you did in your PR.
@prode81 What do you think?

**Comment by prode81** [comment]
I think, this is a valid point. We intentionally left the routes class based within the boilerplate, as everything else has been switched to functional components and we wanted to keep one example for API usage within a class component.

But as we have 2 routes, changing one to a functional component seems to be a great improvement. Personally, I don't care which one.

**Comment by jens-ox** [comment]
Yes, I agree, showing all possible usages is nice - I'm just not sure if it makes sense to encourage people to write new components using the class structure.

**Comment by prode81** [comment]
@jens-ox valid point, but there still might be reasons to use the class-components within a project, for instance if you are migrating an old project in smaller iterations.

So, my suggestion would be to make the home-route a functional component, as it is the best-practice but to keep the DemoContent route as class-component.
We might add a comment to the route, that it only serves as example for class components for compatibility reasons/backwards compatibility.

**Comment by jens-ox** [comment]
I agree on the migration stuff. Updated the PR accordingly :slightly_smiling_face:

**Review by prode81 — DISMISSED** [review]

**Comment by prode81** [comment]
Awesome, thank you @jens-ox!

I leave @ebual the honor of the final word and to merge the first community based PR if he has no further annotations to the code.

**Comment by jens-ox** [comment]
Sorry, mis-pushed something to my fork :sweat_smile:

**Review by prode81 — APPROVED** [review]

**Review by ebual — APPROVED** [review]

**Pull request merged**
